/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DataVerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "ORACLE_ROLE"
      | "RA_ROLE"
      | "anchorVC"
      | "commitReading"
      | "commitments"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "hasValidVerdict"
      | "isVCAnchored"
      | "oraclePosted"
      | "oracleValid"
      | "postVerdict"
      | "renounceRole"
      | "revokeRole"
      | "storeVCCommitment"
      | "submitOracleVerification"
      | "submitRECommitment"
      | "supportsInterface"
      | "vcToReading"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OracleVerdictPosted"
      | "ReadingCommitted"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "VCAnchored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORACLE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "RA_ROLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "anchorVC",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitReading",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasValidVerdict",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVCAnchored",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oraclePosted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleValid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "postVerdict",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeVCCommitment",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitOracleVerification",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRECommitment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vcToReading",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "RA_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "anchorVC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitReading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasValidVerdict",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVCAnchored",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oraclePosted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "postVerdict",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storeVCCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitOracleVerification",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRECommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vcToReading",
    data: BytesLike
  ): Result;
}

export namespace OracleVerdictPostedEvent {
  export type InputTuple = [readingHash: BytesLike, isValid: boolean];
  export type OutputTuple = [readingHash: string, isValid: boolean];
  export interface OutputObject {
    readingHash: string;
    isValid: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReadingCommittedEvent {
  export type InputTuple = [readingHash: BytesLike, committer: AddressLike];
  export type OutputTuple = [readingHash: string, committer: string];
  export interface OutputObject {
    readingHash: string;
    committer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VCAnchoredEvent {
  export type InputTuple = [vcHash: BytesLike, readingHash: BytesLike];
  export type OutputTuple = [vcHash: string, readingHash: string];
  export interface OutputObject {
    vcHash: string;
    readingHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DataVer extends BaseContract {
  connect(runner?: ContractRunner | null): DataVer;
  waitForDeployment(): Promise<this>;

  interface: DataVerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  ORACLE_ROLE: TypedContractMethod<[], [string], "view">;

  RA_ROLE: TypedContractMethod<[], [string], "view">;

  anchorVC: TypedContractMethod<
    [vcHash: BytesLike, readingHash: BytesLike],
    [void],
    "nonpayable"
  >;

  commitReading: TypedContractMethod<
    [readingHash: BytesLike],
    [void],
    "nonpayable"
  >;

  commitments: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hasValidVerdict: TypedContractMethod<
    [readingHash: BytesLike],
    [boolean],
    "view"
  >;

  isVCAnchored: TypedContractMethod<[vcHash: BytesLike], [boolean], "view">;

  oraclePosted: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  oracleValid: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  postVerdict: TypedContractMethod<
    [readingHash: BytesLike, valid: boolean],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  storeVCCommitment: TypedContractMethod<
    [vcHash: BytesLike, readingHash: BytesLike],
    [void],
    "nonpayable"
  >;

  submitOracleVerification: TypedContractMethod<
    [readingHash: BytesLike, isValid: boolean],
    [void],
    "nonpayable"
  >;

  submitRECommitment: TypedContractMethod<
    [readingHash: BytesLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  vcToReading: TypedContractMethod<[vcHash: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ORACLE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RA_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "anchorVC"
  ): TypedContractMethod<
    [vcHash: BytesLike, readingHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitReading"
  ): TypedContractMethod<[readingHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commitments"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasValidVerdict"
  ): TypedContractMethod<[readingHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVCAnchored"
  ): TypedContractMethod<[vcHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "oraclePosted"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "oracleValid"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "postVerdict"
  ): TypedContractMethod<
    [readingHash: BytesLike, valid: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storeVCCommitment"
  ): TypedContractMethod<
    [vcHash: BytesLike, readingHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitOracleVerification"
  ): TypedContractMethod<
    [readingHash: BytesLike, isValid: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitRECommitment"
  ): TypedContractMethod<[readingHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "vcToReading"
  ): TypedContractMethod<[vcHash: BytesLike], [string], "view">;

  getEvent(
    key: "OracleVerdictPosted"
  ): TypedContractEvent<
    OracleVerdictPostedEvent.InputTuple,
    OracleVerdictPostedEvent.OutputTuple,
    OracleVerdictPostedEvent.OutputObject
  >;
  getEvent(
    key: "ReadingCommitted"
  ): TypedContractEvent<
    ReadingCommittedEvent.InputTuple,
    ReadingCommittedEvent.OutputTuple,
    ReadingCommittedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "VCAnchored"
  ): TypedContractEvent<
    VCAnchoredEvent.InputTuple,
    VCAnchoredEvent.OutputTuple,
    VCAnchoredEvent.OutputObject
  >;

  filters: {
    "OracleVerdictPosted(bytes32,bool)": TypedContractEvent<
      OracleVerdictPostedEvent.InputTuple,
      OracleVerdictPostedEvent.OutputTuple,
      OracleVerdictPostedEvent.OutputObject
    >;
    OracleVerdictPosted: TypedContractEvent<
      OracleVerdictPostedEvent.InputTuple,
      OracleVerdictPostedEvent.OutputTuple,
      OracleVerdictPostedEvent.OutputObject
    >;

    "ReadingCommitted(bytes32,address)": TypedContractEvent<
      ReadingCommittedEvent.InputTuple,
      ReadingCommittedEvent.OutputTuple,
      ReadingCommittedEvent.OutputObject
    >;
    ReadingCommitted: TypedContractEvent<
      ReadingCommittedEvent.InputTuple,
      ReadingCommittedEvent.OutputTuple,
      ReadingCommittedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "VCAnchored(bytes32,bytes32)": TypedContractEvent<
      VCAnchoredEvent.InputTuple,
      VCAnchoredEvent.OutputTuple,
      VCAnchoredEvent.OutputObject
    >;
    VCAnchored: TypedContractEvent<
      VCAnchoredEvent.InputTuple,
      VCAnchoredEvent.OutputTuple,
      VCAnchoredEvent.OutputObject
    >;
  };
}
