/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IProofVerifierInterface extends Interface {
  getFunction(nameOrSignature: "verify"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "verify",
    values: [
      AddressLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export interface IProofVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): IProofVerifier;
  waitForDeployment(): Promise<this>;

  interface: IProofVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  verify: TypedContractMethod<
    [
      to: AddressLike,
      dtHash: BytesLike,
      hiddenCommitment: BytesLike,
      epochIndex: BigNumberish,
      typeCode: BigNumberish,
      qtyKWh: BigNumberish,
      policyNonce: BigNumberish,
      expiry: BigNumberish,
      proof: BytesLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [
      to: AddressLike,
      dtHash: BytesLike,
      hiddenCommitment: BytesLike,
      epochIndex: BigNumberish,
      typeCode: BigNumberish,
      qtyKWh: BigNumberish,
      policyNonce: BigNumberish,
      expiry: BigNumberish,
      proof: BytesLike
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
