/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICrossDomainMessenger,
  ICrossDomainMessengerInterface,
} from "../../../contracts/interfaces/ICrossDomainMessenger";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
      {
        internalType: "uint32",
        name: "gasLimit",
        type: "uint32",
      },
    ],
    name: "sendMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "xDomainMessageSender",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICrossDomainMessenger__factory {
  static readonly abi = _abi;
  static createInterface(): ICrossDomainMessengerInterface {
    return new Interface(_abi) as ICrossDomainMessengerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICrossDomainMessenger {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICrossDomainMessenger;
  }
}
