/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGTokenAnchor,
  IGTokenAnchorInterface,
} from "../../../contracts/interfaces/IGTokenAnchor";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "dtHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "gtAmount",
        type: "uint256",
      },
      {
        internalType: "uint64",
        name: "epochIndex",
        type: "uint64",
      },
      {
        internalType: "uint16",
        name: "typeCode",
        type: "uint16",
      },
      {
        internalType: "uint256",
        name: "qtyKWh",
        type: "uint256",
      },
    ],
    name: "recordMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGTokenAnchor__factory {
  static readonly abi = _abi;
  static createInterface(): IGTokenAnchorInterface {
    return new Interface(_abi) as IGTokenAnchorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGTokenAnchor {
    return new Contract(address, _abi, runner) as unknown as IGTokenAnchor;
  }
}
