/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IProofVerifier,
  IProofVerifierInterface,
} from "../../../contracts/interfaces/IProofVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "dtHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "hiddenCommitment",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "epochIndex",
        type: "uint64",
      },
      {
        internalType: "uint16",
        name: "typeCode",
        type: "uint16",
      },
      {
        internalType: "uint256",
        name: "qtyKWh",
        type: "uint256",
      },
      {
        internalType: "uint128",
        name: "policyNonce",
        type: "uint128",
      },
      {
        internalType: "uint64",
        name: "expiry",
        type: "uint64",
      },
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IProofVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IProofVerifierInterface {
    return new Interface(_abi) as IProofVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProofVerifier {
    return new Contract(address, _abi, runner) as unknown as IProofVerifier;
  }
}
