/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockCrossDomainMessenger,
  MockCrossDomainMessengerInterface,
} from "../../../contracts/mocks/MockCrossDomainMessenger";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "gasLimit",
        type: "uint32",
      },
    ],
    name: "MessageSent",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
      {
        internalType: "uint32",
        name: "gasLimit",
        type: "uint32",
      },
    ],
    name: "sendMessage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "xDomainMessageSender",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610287806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80633dbb202b1461003b5780636e296e4514610050575b600080fd5b61004e610049366004610155565b61006f565b005b600054604080516001600160a01b039092168252519081900360200190f35b600080546001600160a01b031916339081179091556040516001600160a01b03861691907feee621abb842b15d4a9c743701870f3fb19eb4b14f05e9814a0779d8324d281a906100c490879087908790610202565b60405180910390a3600080856001600160a01b031685856040516100e9929190610241565b6000604051808303816000865af19150503d8060008114610126576040519150601f19603f3d011682016040523d82523d6000602084013e61012b565b606091505b50915091508161013d57805160208201fd5b5050600080546001600160a01b031916905550505050565b6000806000806060858703121561016b57600080fd5b84356001600160a01b038116811461018257600080fd5b9350602085013567ffffffffffffffff8082111561019f57600080fd5b818701915087601f8301126101b357600080fd5b8135818111156101c257600080fd5b8860208285010111156101d457600080fd5b602083019550809450505050604085013563ffffffff811681146101f757600080fd5b939692955090935050565b604081528260408201528284606083013760006060848301015260006060601f19601f860116830101905063ffffffff83166020830152949350505050565b818382376000910190815291905056fea26469706673582212208f3f9d369ff1772b6068040bd83ba7dfea0ecdb899acab7ce2dce1346f54ebc764736f6c63430008170033";

type MockCrossDomainMessengerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockCrossDomainMessengerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockCrossDomainMessenger__factory extends ContractFactory {
  constructor(...args: MockCrossDomainMessengerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockCrossDomainMessenger & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockCrossDomainMessenger__factory {
    return super.connect(runner) as MockCrossDomainMessenger__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockCrossDomainMessengerInterface {
    return new Interface(_abi) as MockCrossDomainMessengerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockCrossDomainMessenger {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockCrossDomainMessenger;
  }
}
