/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DemoIssuerVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DOMAIN"
      | "computeDigest"
      | "digest"
      | "issuerSigner"
      | "setIssuerSigner"
      | "verify"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "DOMAIN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "computeDigest",
    values: [
      AddressLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "digest",
    values: [
      AddressLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "issuerSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setIssuerSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [
      AddressLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(functionFragment: "DOMAIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "computeDigest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "digest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issuerSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIssuerSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export interface DemoIssuerVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): DemoIssuerVerifier;
  waitForDeployment(): Promise<this>;

  interface: DemoIssuerVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DOMAIN: TypedContractMethod<[], [string], "view">;

  computeDigest: TypedContractMethod<
    [
      to: AddressLike,
      dtHash: BytesLike,
      hiddenCommitment: BytesLike,
      epochIndex: BigNumberish,
      typeCode: BigNumberish,
      qtyKWh: BigNumberish,
      policyNonce: BigNumberish,
      expiry: BigNumberish
    ],
    [string],
    "view"
  >;

  digest: TypedContractMethod<
    [
      to: AddressLike,
      dtHash: BytesLike,
      hiddenCommitment: BytesLike,
      epochIndex: BigNumberish,
      typeCode: BigNumberish,
      qtyKWh: BigNumberish,
      policyNonce: BigNumberish,
      expiry: BigNumberish
    ],
    [string],
    "view"
  >;

  issuerSigner: TypedContractMethod<[], [string], "view">;

  setIssuerSigner: TypedContractMethod<
    [issuerSigner_: AddressLike],
    [void],
    "nonpayable"
  >;

  verify: TypedContractMethod<
    [
      to: AddressLike,
      dtHash: BytesLike,
      hiddenCommitment: BytesLike,
      epochIndex: BigNumberish,
      typeCode: BigNumberish,
      qtyKWh: BigNumberish,
      policyNonce: BigNumberish,
      expiry: BigNumberish,
      proof: BytesLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DOMAIN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "computeDigest"
  ): TypedContractMethod<
    [
      to: AddressLike,
      dtHash: BytesLike,
      hiddenCommitment: BytesLike,
      epochIndex: BigNumberish,
      typeCode: BigNumberish,
      qtyKWh: BigNumberish,
      policyNonce: BigNumberish,
      expiry: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "digest"
  ): TypedContractMethod<
    [
      to: AddressLike,
      dtHash: BytesLike,
      hiddenCommitment: BytesLike,
      epochIndex: BigNumberish,
      typeCode: BigNumberish,
      qtyKWh: BigNumberish,
      policyNonce: BigNumberish,
      expiry: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "issuerSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setIssuerSigner"
  ): TypedContractMethod<[issuerSigner_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<
    [
      to: AddressLike,
      dtHash: BytesLike,
      hiddenCommitment: BytesLike,
      epochIndex: BigNumberish,
      typeCode: BigNumberish,
      qtyKWh: BigNumberish,
      policyNonce: BigNumberish,
      expiry: BigNumberish,
      proof: BytesLike
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
